# Generated by Django 3.2.2 on 2021-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=22, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('mail_id', models.EmailField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=12, null=True)),
                ('bio', models.CharField(max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
